name: OrangeFox A20 - Builder

on:
  workflow_dispatch:

jobs:
  build:
    name: 🦊 Build OrangeFox 12.1
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    permissions:
      contents: write

    steps:
      - name: Checkout device tree
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build OrangeFox
        uses: UWU-TEAM/UWU-OrangeFox-Builder@v1.0.0
        with:
          USER_NAME: 'Behrooz140'
          USER_EMAIL: 'behiahmadi6@gmail.com'

          DEVICE_TREE: 'https://github.com/Behrooz140/twrp_device_samsung_a20'
          DEVICE_TREE_BRANCH: 'master'

          DEVICE_PATH: 'device/samsung/a20'
          DEVICE_NAME: 'a20'

          BUILD_TARGET: 'recovery'
          GH_RELEASE: 'true'

